### ISSUE TITLE
setStatus does not URL encode string before POST

### ISSUE THREAD

**Issue by echamberlain** [mathworks/thingspeak-particle#4]
setStatus does not URL encode the string before appending it to the POST body, as required by a Content Type of application/x-www-form-urlencoded.

Steps to reproduce:
1. Setup a ThingSpeak channel message.
2. Set the message status to: Battery down to 16% percent charge!
3. Post message to ThingSpeak.

Expected behavior

The message posts to the channel.

Actual behavior

The server returns a 502 error.

Note: Untested, but none of the fields appear to be URL encoded.

**Comment by jasontwinters** [comment]
URL encoding is now done as part of writeField() and writeFields().
