### ISSUE TITLE
'isnan' was not declared in this scope

### ISSUE THREAD

**Issue by akatcha** [mathworks/thingspeak-particle#5]
Veryfing code using this library in Particle Build fails with this error:
```
ThingSpeak/ThingSpeak.h:734:30: error: 'isnan' was not declared in this scope
   if(!isnan(nextWriteLatitude))
                              ^
```

**Comment by jasontwinters** [comment]
I'm not sure what is causing you to see this.  I just confirmed that code using this function builds without errors.  My guess is that your project is not referencing math.h for some reason.
