### ISSUE TITLE
Please update to Libraries 2.0 structure

### ISSUE THREAD

**Issue by ScruffR** [mathworks/thingspeak-particle#6]
Since Particle OS v0.5.3 libraries need to adhere a different structure to be imported.
Could you please migrate this library to that structure and reupload?

To create a library template you can use `particle library create` 

Thanks

**Comment by jasontwinters** [comment]
Thanks for pointing this out.  We'll start working it.

**Comment by jasontwinters** [comment]
migrated to v2 library structure
