### ISSUE TITLE
Library not working with Mesh products

### ISSUE THREAD

**Issue by jimmie11** [mathworks/thingspeak-particle#7]
Thank you for a wonderful library.

I have a very important sketch that was running well on a Particle Electron.  

However, the library is giving the following error on the new Particle Mesh micros (Argon, Boron, Xenon):

`lib/ThingSpeak/ThingSpeak.h:66:3: #error Only Spark Core/Photon/Electron/P1 are supported.`

**Comment by nothans** [comment]
We tried to get early access to the new Particle devices so we could have the library ready. We still have not received shipping confirmation on our pre-order.

**Comment by jimmie11** [comment]
Thank you @nothans .

The .h file may just need to be updated with the statements below but I have not tested it yet.  (Argon(12), Boron(13), Xenon(14)). I am assuming they are all similar to the Photon .....

#elif PLATFORM_ID == 12
	#define PARTICLE_PHOTON
	#define PARTICLE_PHOTONELECTRON
#elif PLATFORM_ID == 13
	#define PARTICLE_PHOTON
	#define PARTICLE_PHOTONELECTRON
#elif PLATFORM_ID == 14
	#define PARTICLE_PHOTON
	#define PARTICLE_PHOTONELECTRON

**Comment by rberkelm** [comment]
There are many mesh holders waiting for this update. Any progress as yet?

**Comment by jasontwinters** [comment]
We just got the hardware.  We're working on it now.

**Comment by jimmie11** [comment]
Hello,

Thank you.

I made the changes below and it has been working for the last few weeks:

**I realize the code below is not clean, but it works because of the compatibility between the Photon/Electron and the Argon/Boron/Xenon.**

// Create platform defines for Particle devices
#if PLATFORM_ID == 0
	#define PARTICLE_CORE
#elif PLATFORM_ID == 6
	#define PARTICLE_PHOTON
	#define PARTICLE_PHOTONELECTRON
#elif PLATFORM_ID == 8
	#define PARTICLE_P1
	#define PARTICLE_PHOTONELECTRON
#elif PLATFORM_ID == 10
	#define PARTICLE_ELECTRON
	#define PARTICLE_PHOTONELECTRON
#elif PLATFORM_ID == 12
	#define PARTICLE_PHOTON
	#define PARTICLE_PHOTONELECTRON
#elif PLATFORM_ID == 13
	#define PARTICLE_PHOTON
	#define PARTICLE_PHOTONELECTRON
#elif PLATFORM_ID == 14
	#define PARTICLE_PHOTON
	#define PARTICLE_PHOTONELECTRON
#else
	#error Only Spark Core/Photon/Electron/P1 are supported.
#endif

**Comment by jasontwinters** [comment]
Added support for Argon and Boron with v1.5.0.  Xenon isn't supported since TCP connections are not possible from non-gateway devices.
